global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Input;
global using Windows.Foundation;
global using Windows.System;
global using ArtSpace.Core;
global using ArtSpace.Editing;
global using ArtSpace.Controls;
